name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v6
    # - run: nix run nixpkgs.hlint -c hlint src
    - run: nix-build ghcjs.nix --substituters "https://cache.nixos.org https://masser-ebook-manager.cachix.org https://miso-haskell.cachix.org" -A frontend
